name: API CI/CD

on:
  push:
    branches: [timotej]
  pull_request:
    branches: [timotej]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore API dependencies
        run: dotnet restore dj-api/dj-api.csproj

      - name: Build API
        run: dotnet build -c Release --no-restore dj-api/dj-api.csproj

  run-tests:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore API dependencies
        run: dotnet restore dj-api/dj-api.csproj

      - name: Restore DjTests dependencies
        run: dotnet restore DjTests/DjTests.csproj

      - name: Run tests and generate report
        run: |
          dotnet test DjTests/DjTests.csproj --collect:"XPlat Code Coverage" --results-directory ./TestResults --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults

  build-and-push-docker:
    needs: build
    if: (github.ref == 'refs/heads/timotej') && github.event_name == 'push' 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dj-api:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/dj-api:latest
          build-args: |
            ASPNETCORE_URLS=http://+:5152
            ConnectionStrings__DbConnection=${{ secrets.MONGODB_CONNECTION_STRING }}
            JWTSecrets__issuer=${{ secrets.JWT_ISSUER }}
            JWTSecrets__audience=${{ secrets.JWT_AUDIENCE }}
            JWTSecrets__secretKey=${{ secrets.JWT_SECRET_KEY }}
            JWTSecrets__expires=${{ secrets.JWT_EXPIRES }}
